//
// Created by M on 26/07/2023.
//

#ifndef USB_COMMANDS_H
#define USB_COMMANDS_H


#define REQUEST_ACTUAL_TEMPERATURE 0x01
#define SET_TARGET_TEMPERATURE 0x02
#define REQUEST_ACTUAL_HEATER_STATE 0x05
#define SET_HEATER_STATE 0x06
#define REQUEST_ACTUAL_LED_STATE 0x07
#define SET_LED_STATE 0x08
//#define SET_LED_STATE 0x09
#define START_SENDING_PROGRAM 0x0A
#define NEXT_PROGRAM_PACKET 0x0B
#define STOP_SENDING_PROGRAM 0x0C




#endif //USB_COMMANDS_H
