//
// Created by M on 24/07/2023.
//

#ifndef USB_CONFIGURABLES_H
#define USB_CONFIGURABLES_H

#define LED1_BINARY_BLINK 0x00
#define LED1_HEATER_INFO 0x00
#define LED2_CONNECTION_INFO 0x01

#define DEVICE_ID 0xFF
#define CONNECTION_TIMEOUT 4000
#define RX_BUFF_SIZE 16
#endif //USB_CONFIGURABLES_H


#ifndef THERMAL_CONFIGURABLES_H

#define R1 (int)10000

#define PID_PROPORTIONAL (float)0.5
#define PID_INTEGRAL (float)0.5
#define PID_DERIVATIVE (float)0.5
#define MAX_DYNAMIC_ERROR 10 //in

#define TEMP_CORRECTION_INTERVAL (uint16_t)200
#define MAX_PWM_VALUE 65535





#endif //THERMAL_CONFIGURABLES_H
