//
// Created by M on 24/07/2023.
//

#ifndef USB_CONFIGURABLES_H
#define USB_CONFIGURABLES_H

#define LED1_BINARY_BLINK 0x01
#define LED1_HEATER_INFO 0x01
#define LED2_CONNECTION_INFO 0x01

#define DEVICE_ID 0xFF
#define CONNECTION_TIMEOUT 4000

#endif //USB_CONFIGURABLES_H
