//
// Created by M on 26/07/2023.
//

#ifndef USB_COMMANDS_H
#define USB_COMMANDS_H


#define REQUEST_CURRENT_TEMPERATURE 0x01
#define SET_TARGET_TEMPERATURE 0x02
#define REQUEST_CURRENT_HEATER_STATE 0x05
#define SET_HEATER_STATE 0x06
#define REQUEST_CURRENT_LED_STATE 0x07
#define SET_LED_STATE 0x08

#define DISTANCE_ERROR 0x11



#endif //USB_COMMANDS_H
